# Generated by Codex on 2026-01-20

from django.db import migrations, models


def uppercase_request_currency(apps, schema_editor):
    Request = apps.get_model("all_requests", "Request")
    for request in Request.objects.all():
        if request.currency:
            request.currency = request.currency.upper()
            request.save(update_fields=["currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("all_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="currency",
            field=models.CharField(blank=True, choices=[("USD", "USD"), ("SYP", "SYP")], max_length=3, null=True),
        ),
        migrations.RunPython(uppercase_request_currency, migrations.RunPython.noop),
    ]
