# Generated by Django 5.2.3 on 2026-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_requests', '0002_request_currency_uppercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('payment', 'Payment Request'), ('cashout', 'Take Money Request'), ('support', 'Support Request'), ('refund', 'Refund Request'), ('other', 'Other')], default='payment', max_length=20),
        ),
    ]
