# Generated by Codex on 2026-01-20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def backfill_payment_amounts(apps, schema_editor):
    Payment = apps.get_model("payment", "Payment")
    ExchangeRate = apps.get_model("wallets", "ExchangeRate")

    rate = ExchangeRate.objects.order_by("-updated_at").first()
    usd_to_syp = rate.usd_to_syp if rate else Decimal("116")
    syp_to_usd = Decimal("1") / usd_to_syp

    for payment in Payment.objects.all():
        currency = payment.currency or "USD"
        payment.currency = currency
        if payment.final_price is not None:
            if currency == "USD":
                payment.amount_usd = payment.final_price
                payment.amount_syp = (payment.final_price * usd_to_syp).quantize(Decimal("0.01"))
            else:
                payment.amount_syp = payment.final_price
                payment.amount_usd = (payment.final_price * syp_to_usd).quantize(Decimal("0.01"))
            payment.exchange_rate_used = usd_to_syp
        payment.save(update_fields=["currency", "amount_usd", "amount_syp", "exchange_rate_used"])


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_add_wallet_currency_and_multiwallet"),
        ("payment", "0002_alter_payment_options_remove_payment_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="wallet",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="wallets.wallet"),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(choices=[("USD", "US Dollar"), ("SYP", "Syrian Pound")], default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_usd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_syp",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate_used",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.RunPython(backfill_payment_amounts, migrations.RunPython.noop),
    ]
