# Generated by Django 5.2.3 on 2026-07-31 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_add_currency_amounts_wallet'),
        ('store', '0011_price_precision'),
        ('wallets', '0007_wallet_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_pay_status_19fbf4_idx'),
        ),
    ]
