# Generated by Django 4.2.30 on 2026-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_image_available_payment_image_is_fallback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_syp',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='base_price',
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_price',
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
    ]
