# Generated by Django 5.2.7 on 2025-10-21 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_external_product'),
        ('third_party_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['api_config', 'is_active'], name='store_exter_api_con_0de2da_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['external_id'], name='store_exter_externa_a33df1_idx'),
        ),
        migrations.AddIndex(
            model_name='packageprice',
            index=models.Index(fields=['package', 'currency'], name='store_packa_package_cd163b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'section'], name='store_produ_is_acti_b56aac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['external_product'], name='store_produ_externa_166af0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['api_config'], name='store_produ_api_con_fa4860_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['section', 'is_active'], name='store_store_section_86ea47_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['external_product'], name='store_store_externa_fd0b02_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['is_active'], name='store_store_is_acti_3ef03a_idx'),
        ),
    ]
