# Generated by Django merge migration to resolve multiple leaf nodes.
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_agentprofile_earnings_by_currency"),
        ("agents", "0003_agentprofile_currency_limits"),
    ]

    operations = []
