# Generated by Codex on 2026-01-20

from django.db import migrations, models


def uppercase_paymentmethod_currency(apps, schema_editor):
    PaymentMethod = apps.get_model("payment_methods", "PaymentMethod")
    for method in PaymentMethod.objects.all():
        if method.currency:
            method.currency = method.currency.upper()
            method.save(update_fields=["currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("payment_methods", "0002_alter_paymentmethod_icon_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="currency",
            field=models.CharField(choices=[("USD", "US Dollar"), ("SYP", "Syrian Pound")], max_length=3),
        ),
        migrations.RunPython(uppercase_paymentmethod_currency, migrations.RunPython.noop),
    ]
