# Generated by Django 5.2.7 on 2025-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_methods", "0004_add_shipping_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="steps",
            field=models.TextField(blank=True, null=True),
        ),
    ]
