# Generated by Django 5.2.7 on 2025-10-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('syp', 'Syrian Pound')], max_length=10)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('account_details', models.TextField()),
                ('instructions', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_key', models.SlugField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('file', 'File')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payment_methods.paymentmethod')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
