# Generated by Django 4.2.27 on 2025-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyapi',
            name='provider',
            field=models.CharField(choices=[('daily', 'Daily'), ('alfaour', 'Alfaour'), ('alaaeddin', 'Alaaeddin'), ('stark-card', 'Stark-Card')], max_length=50),
        ),
    ]
