# Generated by Django 5.2.3 on 2026-08-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_externalproduct_last_sync_error_and_more'),
        ('third_party_apis', '0002_alter_thirdpartyapi_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('unavailable', 'Unavailable'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('synced_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('unavailable_count', models.PositiveIntegerField(default=0)),
                ('removed_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('run_key', models.CharField(max_length=180, unique=True)),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='third_party_apis.thirdpartyapi')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSyncResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('removed', 'Removed'), ('unavailable', 'Unavailable'), ('invalid', 'Invalid'), ('error', 'Error')], max_length=20)),
                ('changed', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_results', to='store.externalproduct')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='third_party_apis.productsyncrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='productsyncrun',
            index=models.Index(fields=['provider', 'started_at'], name='third_party_provide_19636f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsyncrun',
            index=models.Index(fields=['status', 'started_at'], name='third_party_status_1bf84a_idx'),
        ),
        migrations.AddIndex(
            model_name='productsyncresult',
            index=models.Index(fields=['run', 'status'], name='third_party_run_id_c000aa_idx'),
        ),
        migrations.AddIndex(
            model_name='productsyncresult',
            index=models.Index(fields=['external_id'], name='third_party_externa_d32ed8_idx'),
        ),
    ]
