"""
Django settings for stark_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Only load dotenv files after the environment is selected explicitly.
DJANGO_ENV = os.getenv("DJANGO_ENV")
if not DJANGO_ENV:
    raise ImproperlyConfigured("DJANGO_ENV must be set to development, test, staging, or production.")

DJANGO_ENV = DJANGO_ENV.strip().lower()
if DJANGO_ENV == "development":
    load_dotenv(BASE_DIR / ".env.local", override=False)
elif DJANGO_ENV == "test":
    load_dotenv(BASE_DIR / ".env.test", override=False)
elif DJANGO_ENV in {"staging", "production"}:
    pass
else:
    raise ImproperlyConfigured(
        "DJANGO_ENV must be one of: development, test, staging, production."
    )


def env_value(name, default=None, required=False):
    value = os.getenv(name)
    if value is not None and value != "":
        return value
    if required:
        raise ImproperlyConfigured(f"{name} must be set for DJANGO_ENV={DJANGO_ENV}.")
    return default


def env_bool(name, default=False, required=False):
    value = env_value(name, default=None, required=required)
    if value is None:
        return default
    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a valid boolean value for DJANGO_ENV={DJANGO_ENV}.")


def env_int(name, default=None, required=False, minimum=None, maximum=None):
    value = env_value(name, default=None, required=required)
    if value is None:
        return default
    try:
        parsed = int(str(value).strip())
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f"{name} must be an integer for DJANGO_ENV={DJANGO_ENV}.") from exc
    if minimum is not None and parsed < minimum:
        raise ImproperlyConfigured(f"{name} must be >= {minimum} for DJANGO_ENV={DJANGO_ENV}.")
    if maximum is not None and parsed > maximum:
        raise ImproperlyConfigured(f"{name} must be <= {maximum} for DJANGO_ENV={DJANGO_ENV}.")
    return parsed


def env_list(name, default=None, required=False):
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        if required:
            raise ImproperlyConfigured(f"{name} must be set for DJANGO_ENV={DJANGO_ENV}.")
        return list(default) if default is not None else []
    values = [item.strip() for item in raw.split(",") if item.strip()]
    if not values and required:
        raise ImproperlyConfigured(f"{name} must not be empty for DJANGO_ENV={DJANGO_ENV}.")
    return values or (list(default) if default is not None else [])


def validate_secret_value(name, value, minimum_length=32):
    normalized = (value or "").strip()
    if not normalized:
        raise ImproperlyConfigured(f"{name} must be set for DJANGO_ENV={DJANGO_ENV}.")
    placeholder_markers = {
        "change_me",
        "changeme",
        "replace-me",
        "replace_me",
        "secret",
        "password",
        "django-insecure",
    }
    lowered = normalized.lower()
    if lowered in placeholder_markers or lowered.startswith("django-insecure-") or lowered.startswith("change_me"):
        raise ImproperlyConfigured(f"{name} must be replaced with a real value for DJANGO_ENV={DJANGO_ENV}.")
    if len(normalized) < minimum_length:
        raise ImproperlyConfigured(f"{name} must be at least {minimum_length} characters for DJANGO_ENV={DJANGO_ENV}.")
    return normalized

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value('SECRET_KEY', required=True)
THIRD_PARTY_API_FERNET_KEY = env_value('THIRD_PARTY_API_FERNET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=(DJANGO_ENV == "development"))
USE_SQLITE = env_bool('USE_SQLITE', default=(DJANGO_ENV == "development"))

if DJANGO_ENV in {"staging", "production"}:
    if DEBUG:
        raise ImproperlyConfigured("DEBUG must be False when DJANGO_ENV is staging or production.")
    if USE_SQLITE:
        raise ImproperlyConfigured("USE_SQLITE must be False when DJANGO_ENV is staging or production.")
    SECRET_KEY = validate_secret_value("SECRET_KEY", SECRET_KEY, minimum_length=50)
    THIRD_PARTY_API_FERNET_KEY = validate_secret_value("THIRD_PARTY_API_FERNET_KEY", THIRD_PARTY_API_FERNET_KEY, minimum_length=32)

# Validate required environment variables (log warnings instead of raising to avoid startup crash)
required_env_vars = ['SECRET_KEY', 'THIRD_PARTY_API_FERNET_KEY']
missing_vars = [var for var in required_env_vars if not os.getenv(var)]
if missing_vars:
    print(f"Warning: Missing environment variables: {', '.join(missing_vars)}. Using defaults where possible.")

# Allowed hosts for production
ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    ['localhost', '127.0.0.1'],
    required=DJANGO_ENV in {"staging", "production"},
)
if DJANGO_ENV in {"staging", "production"} and "*" in ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must not contain '*' when DJANGO_ENV is staging or production.")

# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', 
    "django_filters",
    'drf_spectacular',
    "wallets",
    "transactions",
    "store",
    "agents",
    "dashboard",
    "payment_methods",
    'third_party_apis',
    'system',
    'all_requests',
    'qr_code',
    "payment",
    'shipping',
    'finance',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # KEEP THIS - for TOTP devices
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "users.middleware.check_ban_middleware",
    'system.middleware.SystemLogMiddleware', 
    "system.middleware.AdminActionMiddleware", 
]

ROOT_URLCONF = 'stark_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'stark_backend.wsgi.application'

# Database configuration
# Use PostgreSQL whenever database credentials are provided.
if not USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': env_value('DB_ENGINE', default='django.db.backends.postgresql', required=DJANGO_ENV in {"staging", "production"}),
            'NAME': env_value('DB_NAME', required=DJANGO_ENV in {"staging", "production"}),
            'USER': env_value('DB_USER', required=DJANGO_ENV in {"staging", "production"}),
            'PASSWORD': env_value('DB_PASSWORD', required=DJANGO_ENV in {"staging", "production"}),
            'HOST': env_value('DB_HOST', default='127.0.0.1', required=DJANGO_ENV in {"staging", "production"}),
            'PORT': str(env_int('DB_PORT', default=5432, required=DJANGO_ENV in {"staging", "production"}, minimum=1, maximum=65535)),
            'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', default=60, minimum=0),
            'OPTIONS': {
                'sslmode': env_value('DB_SSLMODE', default='prefer', required=False),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Custom user model
AUTH_USER_MODEL = 'users.User'

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.VersionedJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "password_reset_request": "10/hour",
        "password_reset_verify": "30/hour",
        "password_reset_resend": "10/hour",
        "password_change": "10/hour",
        "admin_password_reset": "20/hour"
    }
}

# JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),  # Increased from 60 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# [Rest of your settings... add the remaining content from your original settings.py]

# Internationalization / timezone
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Damascus'
USE_I18N = True
USE_TZ = True

print("Stark Backend Settings Loaded - DEBUG:", DEBUG)
print("DJANGO_ENV:", DJANGO_ENV)
print("Email configured for:", env_value('EMAIL_HOST_USER', default='Not set'))
print("Admin Security: 3-Step Login Enabled")
print("Allowed Hosts:", ALLOWED_HOSTS)
print("Email Backend:", env_value('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend'))
print("SMTP Server:", env_value('EMAIL_HOST', default='smtp.gmail.com'), ":", env_value('EMAIL_PORT', default='587'))

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================
EMAIL_HOST = env_value('EMAIL_HOST', default='smtp.gmail.com', required=DJANGO_ENV in {"staging", "production"})
EMAIL_PORT = env_int('EMAIL_PORT', default=587, required=DJANGO_ENV in {"staging", "production"}, minimum=1, maximum=65535)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=True, required=DJANGO_ENV in {"staging", "production"})
EMAIL_HOST_USER = env_value('EMAIL_HOST_USER', default='', required=DJANGO_ENV in {"staging", "production"})
EMAIL_HOST_PASSWORD = env_value('EMAIL_HOST_PASSWORD', default='', required=DJANGO_ENV in {"staging", "production"})
DEFAULT_FROM_EMAIL = env_value('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = env_value('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')






# For API views, exempt from CSRF


# CORS Settings for frontend-backend communication



# CRITICAL FIXES FOR FRONTEND AUTHENTICATION
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    required=DJANGO_ENV in {"staging", "production"},
)

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET", 
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    required=DJANGO_ENV in {"staging", "production"},
)

# Session settings for frontend compatibility
USE_HTTPS = env_bool('USE_HTTPS', default=(DJANGO_ENV in {"staging", "production"}), required=DJANGO_ENV in {"staging", "production"})
USE_SECURE_PROXY_HEADER = env_bool('USE_SECURE_PROXY_HEADER', default=(DJANGO_ENV in {"staging", "production"}), required=DJANGO_ENV in {"staging", "production"})
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', USE_HTTPS)
SESSION_COOKIE_HTTPONLY = env_bool('SESSION_COOKIE_HTTPONLY', True)
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None' if USE_HTTPS else 'Lax')
SESSION_COOKIE_AGE = 1209600

CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', USE_HTTPS)
CSRF_COOKIE_HTTPONLY = env_bool('CSRF_COOKIE_HTTPONLY', False)
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None' if USE_HTTPS else 'Lax')

if DJANGO_ENV in {"staging", "production"}:
    if not SESSION_COOKIE_SECURE:
        raise ImproperlyConfigured("SESSION_COOKIE_SECURE must be True when DJANGO_ENV is staging or production.")
    if not SESSION_COOKIE_HTTPONLY:
        raise ImproperlyConfigured("SESSION_COOKIE_HTTPONLY must be True when DJANGO_ENV is staging or production.")
    if SESSION_COOKIE_SAMESITE != "None":
        raise ImproperlyConfigured("SESSION_COOKIE_SAMESITE must be None when DJANGO_ENV is staging or production.")
    if not CSRF_COOKIE_SECURE:
        raise ImproperlyConfigured("CSRF_COOKIE_SECURE must be True when DJANGO_ENV is staging or production.")
    if CSRF_COOKIE_HTTPONLY:
        raise ImproperlyConfigured("CSRF_COOKIE_HTTPONLY must be False when DJANGO_ENV is staging or production.")
    if CSRF_COOKIE_SAMESITE != "None":
        raise ImproperlyConfigured("CSRF_COOKIE_SAMESITE must be None when DJANGO_ENV is staging or production.")

# Remove domain restrictions for now
# SESSION_COOKIE_DOMAIN = '.stark-card-app.com'
# CSRF_COOKIE_DOMAIN = '.stark-card-app.com'

# HTTPS settings
if USE_SECURE_PROXY_HEADER:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=USE_HTTPS, required=DJANGO_ENV in {"staging", "production"})

# File upload settings - increased for product images
FILE_UPLOAD_MAX_MEMORY_SIZE = 70 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024  # 10MB

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_BASE_URL = env_value('MEDIA_BASE_URL', default=None)
PRODUCT_IMAGE_PLACEHOLDER_URL = env_value(
    'PRODUCT_IMAGE_PLACEHOLDER_URL', default='/media/placeholders/product-placeholder.svg'
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files configuration (if not set)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Create directories if they don't exist
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(STATIC_ROOT, exist_ok=True)

print("Media and Static configuration loaded")

# =============================================================================
# AUTH/FRONTEND CONFIG
# =============================================================================
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Password-reset security policy. Values are intentionally conservative and configurable.
PASSWORD_RESET_CODE_LIFETIME = env_int('PASSWORD_RESET_CODE_LIFETIME', default=600, minimum=60)
PASSWORD_RESET_RESEND_COOLDOWN = env_int('PASSWORD_RESET_RESEND_COOLDOWN', default=60, minimum=1)
PASSWORD_RESET_MAX_ATTEMPTS = env_int('PASSWORD_RESET_MAX_ATTEMPTS', default=5, minimum=1)
PASSWORD_RESET_REQUESTS_PER_HOUR = env_int('PASSWORD_RESET_REQUESTS_PER_HOUR', default=5, minimum=1)
PASSWORD_RESET_REQUESTS_PER_DAY = env_int('PASSWORD_RESET_REQUESTS_PER_DAY', default=10, minimum=1)
PASSWORD_RESET_AUTHORIZATION_LIFETIME = env_int('PASSWORD_RESET_AUTHORIZATION_LIFETIME', default=600, minimum=60)
