# Generated by Django 5.2.7 on 2025-10-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminsecurity_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsecurity',
            name='is_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='adminsecurity',
            name='totp_secret',
        ),
    ]
