# Generated by Django 4.2.27 on 2025-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_category_assigned_at_user_category_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercategory',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marks this category as the default assigned to newly created users'),
        ),
    ]
