# Generated by Django 4.2.27 on 2025-12-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customercategory_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminloginsession',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='adminloginsession',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='adminsecurity',
            name='backup_codes',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_BAN', 'User Banned'), ('USER_UNBAN', 'User Unbanned'), ('ROLE_CHANGE', 'Role Changed'), ('CATEGORY_ASSIGN', 'Category Assigned'), ('PASSWORD_CHANGE', 'Password Changed'), ('SECOND_PASSWORD_SET', 'Second Password Set'), ('SECOND_PASSWORD_CHANGE', 'Second Password Changed')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_audit_user_id_0bc804_idx'), models.Index(fields=['action', 'created_at'], name='users_audit_action_9b343e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='users_audit_resourc_156f16_idx')],
            },
        ),
    ]
