# Generated by Codex on 2025-12-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_adminloginsession_otp_code_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customercategory",
            name="users_custo_is_acti_38210b_idx",
        ),
        migrations.RemoveField(
            model_name="customercategory",
            name="order",
        ),
        migrations.AlterModelOptions(
            name="customercategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Customer Category",
                "verbose_name_plural": "Customer Categories",
            },
        ),
    ]
