# Generated by Django 5.2.3 on 2026-08-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_exchange_rate_quote_and_more'),
        ('users', '0017_remove_legacy_password_reset_token'),
        ('wallets', '0008_exchangeratequote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_BAN', 'User Banned'), ('USER_UNBAN', 'User Unbanned'), ('ROLE_CHANGE', 'Role Changed'), ('CATEGORY_ASSIGN', 'Category Assigned'), ('PASSWORD_CHANGE', 'Password Changed'), ('SECOND_PASSWORD_SET', 'Second Password Set'), ('SECOND_PASSWORD_CHANGE', 'Second Password Changed'), ('CUSTOMER_ADMIN_ACTION', 'Customer Administration Action'), ('BALANCE_ADJUSTMENT', 'Balance Adjustment'), ('SESSION_REVOKE', 'Sessions Revoked')], max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('SYP', 'SYP')], max_length=3)),
                ('reason', models.TextField()),
                ('decision_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustment', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_balance_adjustments', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'status'], name='users_custo_target__80b9f5_idx'), models.Index(fields=['status', 'created_at'], name='users_custo_status_177e5a_idx')],
            },
        ),
    ]
