# Generated by Django 4.2.27 on 2025-12-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_remove_payment_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0004_alter_exchangerate_options_wallet_created_at_and_more'),
        ('transactions', '0003_add_exchange_rate_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='agent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Reference ID from external payment processor', max_length=255, null=True, verbose_name='External Reference'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Related payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='For transfer transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, help_text='For refunds or related transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='transactions.transaction', verbose_name='Related Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (USD)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_syp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated SYP equivalent', max_digits=14, null=True, verbose_name='Amount (SYP)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='USD to SYP rate at transaction time', max_digits=16, null=True, verbose_name='Exchange Rate Used'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, help_text='Additional information about this transaction', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_wallet',
            field=models.ForeignKey(blank=True, help_text="Recipient's wallet for transfers", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='wallets.wallet', verbose_name='Recipient Wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('commission', 'Commission'), ('fee', 'Fee')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet', verbose_name='Wallet'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='transaction_user_id_f5864b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_ed11cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_67ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_reference'], name='transaction_externa_6c3fd2_idx'),
        ),
    ]
