# Generated by Codex on 2026-01-20

from decimal import Decimal
from django.db import migrations, models


def backfill_transaction_amounts(apps, schema_editor):
    Transaction = apps.get_model("transactions", "Transaction")
    ExchangeRate = apps.get_model("wallets", "ExchangeRate")

    rate = ExchangeRate.objects.order_by("-updated_at").first()
    usd_to_syp = rate.usd_to_syp if rate else Decimal("116")
    syp_to_usd = Decimal("1") / usd_to_syp

    for tx in Transaction.objects.all():
        currency = tx.currency or "USD"
        tx.currency = currency
        if tx.amount is not None:
            if currency == "USD":
                tx.amount_usd = tx.amount
                if tx.amount_syp is None:
                    tx.amount_syp = (tx.amount * usd_to_syp).quantize(Decimal("0.01"))
            else:
                tx.amount_syp = tx.amount
                tx.amount_usd = (tx.amount * syp_to_usd).quantize(Decimal("0.01"))
            tx.exchange_rate_used = usd_to_syp
        tx.save(update_fields=["currency", "amount_usd", "amount_syp", "exchange_rate_used"])


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_add_wallet_currency_and_multiwallet"),
        ("transactions", "0004_alter_transaction_options_remove_transaction_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(choices=[("USD", "US Dollar"), ("SYP", "Syrian Pound")], default="USD", max_length=3, verbose_name="Currency"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount_usd",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Amount (USD)"),
        ),
        migrations.RunPython(backfill_transaction_amounts, migrations.RunPython.noop),
    ]
