# Generated by Django 4.2.27 on 2026-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_add_currency_amount_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated USD equivalent', max_digits=14, null=True, verbose_name='Amount (USD)'),
        ),
    ]
