# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_transaction_precision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("purchase", "Purchase"),
                    ("cashout", "Cashout"),
                    ("refund", "Refund"),
                    ("commission", "Commission"),
                    ("fee", "Fee"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
    ]
