# Generated by Django 5.2.3 on 2026-07-31 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_payment_pay_status_19fbf4_idx'),
        ('transactions', '0008_add_cashout_transaction_type'),
        ('wallets', '0007_wallet_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status', 'created_at'], name='transaction_transac_731d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='transaction_status_d2f80b_idx'),
        ),
    ]
