# Generated by Django 5.2.3 on 2026-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_balance_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('purchase', 'Purchase'), ('purchase_hold', 'Purchase Hold'), ('cashout', 'Cashout'), ('refund', 'Refund'), ('commission', 'Commission'), ('fee', 'Fee')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
