# Generated by Django 5.2.3 on 2026-07-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_transaction_type'),
        ('wallets', '0008_exchangeratequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.exchangeratequote'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_side',
            field=models.CharField(blank=True, choices=[('PLATFORM_BUYS_BASE', 'Platform buys base'), ('PLATFORM_SELLS_BASE', 'Platform sells base'), ('NONE', 'No conversion')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rounding_mode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
