# Generated by Django 5.2.3 on 2026-08-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_exchange_rate_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='image_is_fallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='image_source',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
