# Generated by Django 5.2.7 on 2025-10-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in the selected currency', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SYP', 'Syrian Pound')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SYP', 'Syrian Pound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_prices',
            field=models.TextField(blank=True, help_text='Comma-separated prices in selected currency: 10,15,20', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_amount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the minimum amount in the selected currency', max_digits=10, null=True),
        ),
    ]
