# Generated by Django 5.2.7 on 2025-10-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_section_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_product',
            field=models.ForeignKey(blank=True, help_text='Link to external product from API', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_products', to='store.externalproduct'),
        ),
    ]
