# Generated by Django 4.2.27 on 2025-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_favorite_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
