# Generated by Django 4.2.27 on 2025-12-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_externalproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
