# Generated by Django 4.2.27 on 2025-12-26 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_apis', '0002_alter_thirdpartyapi_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_alter_externalproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='packageprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='packageprice',
            name='package',
        ),
        migrations.AlterModelOptions(
            name='externalproduct',
            options={'ordering': ['category', 'name'], 'verbose_name': 'External Product', 'verbose_name_plural': 'External Products'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_en'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productrequirement',
            options={'ordering': ['order', 'field_name'], 'verbose_name': 'Product Requirement', 'verbose_name_plural': 'Product Requirements'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name_en'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['name'], 'verbose_name': 'Store Product', 'verbose_name_plural': 'Store Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='customization_prices',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_amount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated values for select fields', null=True, verbose_name='Options (for select fields)'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='api_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_products', to='third_party_apis.thirdpartyapi', verbose_name='API Configuration'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price from the external API', max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='category',
            field=models.CharField(blank=True, help_text='Category from external API', max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='external_data',
            field=models.JSONField(default=dict, help_text='Additional data from external API (JSON format)', verbose_name='External Data'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='external_id',
            field=models.CharField(help_text='ID from the external API', max_length=255, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='last_synced',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Synced'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='externalproduct',
            name='required_fields_json',
            field=models.JSONField(default=list, help_text='Fields required by the external API (JSON format)', verbose_name='Required Fields'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='api_config',
            field=models.ForeignKey(blank=True, help_text='API configuration for external services', null=True, on_delete=django.db.models.deletion.SET_NULL, to='third_party_apis.thirdpartyapi', verbose_name='API Configuration'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='For amount-based: Price per unit. For customization-based: Not used.', max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SYP', 'Syrian Pound')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_options',
            field=models.TextField(blank=True, help_text="JSON format: [{'option': 'Option 1', 'price': '10'}, ...]", null=True, verbose_name='Customization Options'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_product',
            field=models.ForeignKey(blank=True, help_text='Link to external product from API (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_products', to='store.externalproduct', verbose_name='External Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount user can purchase (for amount-based products)', max_digits=10, null=True, verbose_name='Maximum Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount user can purchase (for amount-based products)', max_digits=10, null=True, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('amount_based', 'Amount Based'), ('customization_based', 'Customization Based')], default='amount_based', max_length=20, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='field_name',
            field=models.CharField(max_length=255, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('id', 'ID'), ('textarea', 'Text Area'), ('url', 'URL'), ('date', 'Date'), ('select', 'Select')], default='text', max_length=20, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='productrequirement',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Placeholder Text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='father_section',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a main section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='store.section', verbose_name='Parent Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Section Image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_ar',
            field=models.CharField(max_length=255, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Custom description for this product', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='external_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='store.externalproduct', verbose_name='External Product'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='name',
            field=models.CharField(help_text='Custom name for this product', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Custom price for this product', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='store.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['category', 'is_active'], name='store_exter_categor_1f1a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['is_active'], name='store_exter_is_acti_b3be18_idx'),
        ),
        migrations.AddIndex(
            model_name='externalproduct',
            index=models.Index(fields=['last_synced'], name='store_exter_last_sy_be7ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='store_favor_user_id_d088a1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['product', 'created_at'], name='store_favor_product_de8504_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='store_produ_product_515698_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['currency', 'is_active'], name='store_produ_currenc_05c362_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_en'], name='store_produ_name_en_8a3bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_ar'], name='store_produ_name_ar_2f070a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='store_produ_created_5555f3_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequirement',
            index=models.Index(fields=['product', 'order'], name='store_produ_product_98176c_idx'),
        ),
        migrations.AddIndex(
            model_name='productrequirement',
            index=models.Index(fields=['field_type'], name='store_produ_field_t_3dbaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active'], name='store_secti_is_acti_3b8381_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['father_section', 'is_active'], name='store_secti_father__3d9846_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name_en'], name='store_secti_name_en_06f300_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name_ar'], name='store_secti_name_ar_2535d9_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['created_at'], name='store_store_created_bb99e5_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['name'], name='store_store_name_2fbdb2_idx'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackagePrice',
        ),
    ]
