# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_package_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeproduct",
            name="currency",
            field=models.CharField(choices=[("USD", "US Dollar"), ("SYP", "Syrian Pound")], default="USD", max_length=3, verbose_name="Currency"),
        ),
    ]
