# Generated by Django 4.2.27 on 2026-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeproduct_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customization_options',
            field=models.TextField(blank=True, help_text="Comma-separated values, e.g. '200,250,300'", null=True, verbose_name='Customization Options'),
        ),
    ]
