# Generated by Django 5.2.3 on 2026-08-01 14:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_price_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional markup on the native base price; zero means no additional profit.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))], verbose_name='Additional Product Profit Percentage'),
        ),
    ]
