# Generated by Django 5.2.3 on 2026-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_product_profit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproduct',
            name='last_sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='externalproduct',
            name='last_sync_error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='externalproduct',
            name='provider_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unavailable', 'Unavailable'), ('removed', 'Removed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='administrator_disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled by administrator'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unavailable', 'Unavailable'), ('removed', 'Removed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='administrator_disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled by administrator'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='provider_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unavailable', 'Unavailable'), ('removed', 'Removed')], default='active', max_length=20),
        ),
    ]
