# Generated by Django 4.2.30 on 2026-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_externalproduct_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=12, help_text='Price from the external API', max_digits=24, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=12, help_text='Price per unit for amount-based and customization-based products.', max_digits=24, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.DecimalField(decimal_places=12, help_text='Custom price for this product', max_digits=24, verbose_name='Price'),
        ),
    ]
