# Generated by Django 4.2.27 on 2025-12-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0003_alter_wallet_options_alter_wallet_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Exchange Rate', 'verbose_name_plural': 'Exchange Rates'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Available Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pending Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallets_wal_user_id_006796_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['available_balance'], name='wallets_wal_availab_698b2e_idx'),
        ),
    ]
