# Generated by Codex on 2026-01-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_currency_wallets(apps, schema_editor):
    Wallet = apps.get_model("wallets", "Wallet")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    # Backfill existing wallets to USD
    Wallet.objects.filter(currency__isnull=True).update(currency="USD")

    # Ensure each user has USD and SYP wallets
    for user in User.objects.all():
        Wallet.objects.get_or_create(user=user, currency="USD", defaults={
            "available_balance": 0,
            "pending_balance": 0,
        })
        Wallet.objects.get_or_create(user=user, currency="SYP", defaults={
            "available_balance": 0,
            "pending_balance": 0,
        })


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallets", "0004_alter_exchangerate_options_wallet_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(choices=[("USD", "US Dollar"), ("SYP", "Syrian Pound")], default="USD", max_length=3, verbose_name="Currency"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallets", to=settings.AUTH_USER_MODEL, verbose_name="User"),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "currency")},
        ),
        migrations.RunPython(create_currency_wallets, migrations.RunPython.noop),
    ]
