# Generated by Django 4.2.27 on 2026-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_add_wallet_currency_and_multiwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Available Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Pending Balance'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='wallets_wal_currenc_7dd088_idx'),
        ),
    ]
