# Generated by Django 5.2.3 on 2026-07-31 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_zero_spread_quote(apps, schema_editor):
    ExchangeRate = apps.get_model("wallets", "ExchangeRate")
    ExchangeRateQuote = apps.get_model("wallets", "ExchangeRateQuote")
    if ExchangeRateQuote.objects.filter(
        base_currency="USD", quote_currency="SYP", status="active"
    ).exists():
        return
    legacy = ExchangeRate.objects.filter(usd_to_syp__gt=0).order_by("-updated_at").first()
    if not legacy:
        # Deliberately do not invent a production quote or use the old 116 fallback.
        return
    ExchangeRateQuote.objects.create(
        base_currency="USD",
        quote_currency="SYP",
        platform_buy_base_rate=legacy.usd_to_syp,
        platform_sell_base_rate=legacy.usd_to_syp,
        status="active",
        source="migration",
        effective_at=legacy.updated_at,
        activation_note="Zero-spread quote backfilled from the latest valid legacy ExchangeRate.",
        version=1,
    )


def preserve_quotes_on_reverse(apps, schema_editor):
    # Quote history is intentionally preserved; rollback removes only the schema.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_wallet_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(default='SYP', max_length=3)),
                ('platform_buy_base_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('platform_sell_base_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('migration', 'Migration'), ('system', 'System')], default='manual', max_length=12)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rate_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version', '-created_at'],
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', 'status'], name='wallets_exc_base_cu_b1ce8d_idx'), models.Index(fields=['base_currency', 'quote_currency', 'effective_at'], name='wallets_exc_base_cu_20d224_idx'), models.Index(fields=['base_currency', 'quote_currency', 'version'], name='wallets_exc_base_cu_42a042_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='exchange_quote_distinct_currencies'), models.CheckConstraint(condition=models.Q(('platform_buy_base_rate__gt', 0)), name='exchange_quote_buy_rate_positive'), models.CheckConstraint(condition=models.Q(('platform_sell_base_rate__gt', 0)), name='exchange_quote_sell_rate_positive'), models.CheckConstraint(condition=models.Q(('platform_sell_base_rate__gte', models.F('platform_buy_base_rate'))), name='exchange_quote_sell_not_below_buy'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('base_currency', 'quote_currency'), name='exchange_quote_one_active_pair')],
            },
        ),
        migrations.RunPython(backfill_zero_spread_quote, preserve_quotes_on_reverse),
    ]
