# Generated by Django 5.2.7 on 2025-10-18 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('daily', 'Daily'), ('alfaour', 'Alfaour'), ('alaaeddin', 'Alaaeddin')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('base_url', models.URLField()),
                ('encrypted_api_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Third Party API',
                'verbose_name_plural': 'Third Party APIs',
                'db_table': 'third_party_apis',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='third_party_provide_9c6468_idx'), models.Index(fields=['is_active', 'priority'], name='third_party_is_acti_dfbc24_idx')],
            },
        ),
        migrations.CreateModel(
            name='APITransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(default=dict)),
                ('endpoint_used', models.CharField(max_length=255)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='third_party_apis.thirdpartyapi')),
            ],
            options={
                'verbose_name': 'API Transaction',
                'verbose_name_plural': 'API Transactions',
                'db_table': 'api_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_config', 'created_at'], name='api_transac_api_con_35f86d_idx'), models.Index(fields=['success', 'created_at'], name='api_transac_success_fad6fe_idx'), models.Index(fields=['external_transaction_id'], name='api_transac_externa_f96189_idx')],
            },
        ),
    ]
