# Generated by Django 4.2.27 on 2025-12-18 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shipping Request', 'verbose_name_plural': 'Shipping Requests'},
        ),
        migrations.AddField(
            model_name='shipping',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shippings', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('syp', 'SYP')], default='usd', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['status', 'created_at'], name='shipping_sh_status_3b3a67_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['user', 'status'], name='shipping_sh_user_id_f95c20_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['transaction_ref'], name='shipping_sh_transac_563a12_idx'),
        ),
    ]
