# Generated by Codex on 2026-01-20

from django.db import migrations, models


def uppercase_shipping_currency(apps, schema_editor):
    Shipping = apps.get_model("shipping", "Shipping")
    for shipping in Shipping.objects.all():
        if shipping.currency:
            shipping.currency = shipping.currency.upper()
            shipping.save(update_fields=["currency"])


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_alter_shipping_options_shipping_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipping",
            name="currency",
            field=models.CharField(choices=[("USD", "USD"), ("SYP", "SYP")], default="USD", max_length=3),
        ),
        migrations.RunPython(uppercase_shipping_currency, migrations.RunPython.noop),
    ]
