# Generated by Django 5.2.3 on 2026-07-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_add_shipping_scenarios'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentadminshippingrequest',
            new_name='shipping_ag_status_679641_idx',
            old_name='shipping_agentadmin_status_1b9c01_idx',
        ),
        migrations.RenameIndex(
            model_name='agentadminshippingrequest',
            new_name='shipping_ag_agent_i_8b36c0_idx',
            old_name='shipping_agentadmin_agent__df7c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentshippingrequest',
            new_name='shipping_ag_status_e470e6_idx',
            old_name='shipping_agent_status_1f4ed8_idx',
        ),
        migrations.RenameIndex(
            model_name='agentshippingrequest',
            new_name='shipping_ag_user_id_70aa5c_idx',
            old_name='shipping_agent_user_id_4b3f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='agentshippingrequest',
            new_name='shipping_ag_agent_i_bde54a_idx',
            old_name='shipping_agent_agent_i_e2d9ce_idx',
        ),
        migrations.RenameIndex(
            model_name='standardshippingrequest',
            new_name='shipping_st_status_4ddf80_idx',
            old_name='shipping_stand_status_7a0a31_idx',
        ),
        migrations.RenameIndex(
            model_name='standardshippingrequest',
            new_name='shipping_st_user_id_9b4ad9_idx',
            old_name='shipping_stand_user_id_78a338_idx',
        ),
    ]
