# Generated by Django 5.2.7 on 2025-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminloginsession_adminsecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsecurity',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsecurity',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
