# Generated by Django 5.2.7 on 2025-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_adminsecurity_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsecurity',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
