# Generated by Django 4.2.27 on 2025-12-27 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-created_at'], 'verbose_name': 'إعلان', 'verbose_name_plural': 'الإعلانات'},
        ),
        migrations.AlterModelOptions(
            name='lastaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'آخر إجراء', 'verbose_name_plural': 'آخر الإجراءات'},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل النظام', 'verbose_name_plural': 'سجلات النظام'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='section',
        ),
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='عنوان الإعلان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='لون الخلفية'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='font_size',
            field=models.PositiveIntegerField(default=14, verbose_name='حجم الخط'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/', verbose_name='صورة الإعلان'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الإعلان'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(verbose_name='نص الإعلان'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text_color',
            field=models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود')], default='black', max_length=5, verbose_name='لون النص'),
        ),
    ]
