# Generated by Django 5.2.3 on 2026-09-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notification_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='system_noti_recipie_77c36f_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='system_noti_recipie_4cf518_idx',
            old_name='notif_recipient_date_idx',
        ),
        migrations.AddField(
            model_name='pushdevicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushdevicetoken',
            index=models.Index(fields=['user', 'is_active'], name='system_push_user_id_149dae_idx'),
        ),
    ]
